
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: demo2

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo2
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: demo2
    networking.gke.io/v1beta1.FrontendConfig: demo2
    networking.gke.io/managed-certificates: demo2
spec:
  defaultBackend:
    service:
      name: demo2
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo2
spec:
  type: LoadBalancer
  selector:
    app: demo2
  ports:
  - port: 80
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  labels:
    app: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - name: demo2
        image: us-central1-docker.pkg.dev/uas-example-3/uas-example-be/app:latest